---
## This worflow will build the litmus-e2e image for every new commit.
name: Air-gapped Support
on:
  workflow_dispatch:

jobs:
  air-gapped-job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # Pulling kind/node image
      - run: |
          mkdir assets
          cp ./litmus/kind.sh assets/
          cp ./litmus/utils.sh assets/
          docker pull kindest/node:v1.21.1 && docker save kindest/node:v1.21.1 -o assets/node.tar
          docker pull registry:2 && docker save registry:2 -o assets/registry.tar
          docker pull litmuschaos/litmusportal-frontend:ci && docker save litmuschaos/litmusportal-frontend:ci -o assets/litmusportal-frontend.tar
          docker pull litmuschaos/litmusportal-server:ci && docker save litmuschaos/litmusportal-server:ci -o assets/litmusportal-server.tar
          docker pull litmuschaos/litmusportal-auth-server:ci && docker save litmuschaos/litmusportal-auth-server:ci -o assets/litmusportal-auth-server.tar
          curl https://raw.githubusercontent.com/litmuschaos/litmus/master/litmus-portal/cluster-k8s-manifest.yml --output assets/litmus-portal-setup.yml

      # Creating a cluster with network none & mounting all assets inside the container as a host.
      - run: |
          docker run -t --rm --network none -v "$(pwd)"/assets:/kind-air-gap/assets --privileged jonsy13/kind-air-gap:latest /bin/bash -c "ls && cd assets && chmod +x kind.sh && ./kind.sh"
