---
## This worflow will build the litmus-e2e image for every new commit. 
name: Air-gapped Support
on:
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-20.04
    steps:
    # Pulling kind/node image
      - run: |
          mkdir assets
          cp litmus/kind.sh assets/
          docker pull kindest/node:v1.21.1 && docker save kindest/node:v1.21.1 -o assets/node.tar

    # Creating a cluster with network none & mounting all assets inside the container as a host.
      - run: |
          docker run -t --rm --network none -v "$(pwd)"/assets:/kind-air-gap/assets --privileged jonsy13/kind-air-gap:latest /bin/bash -c "ls && cd assets && chmod +x kind.sh && ./kind.sh"
                